//
//  Articles.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class Articles: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _title: String?
    var _uRL: String?
    
    class func dynamoDBTableName() -> String {

        return "waterboy-mobilehub-1881338416-Articles"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_title" : "Title",
               "_uRL" : "URL",
        ]
    }
}
