//
//  Articles.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class WaterboyArticles: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _sport: String?
    var _articleLink: String?
    var _articleName: String?
        
    class func dynamoDBTableName() -> String {
        
        //return "waterboy-mobilehub-1881338416-WaterboyArticles"
        return "WaterboyArticles"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {
        print("_sport")
        return "_sport"
        
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_userId" : "userId",
            "_sport" : "Sport",
            "_articleLink" : "ArticleLink",
            "_articleName" : "ArticleName",
        ]
    }
}

